# Generated by Django 3.0.6 on 2020-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=500)),
                ('releasedON', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='images/')),
                ('disc', models.CharField(default='', max_length=500)),
                ('platform', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=500)),
                ('releasedON', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='images/')),
                ('disc', models.CharField(default='', max_length=500)),
                ('platform', models.CharField(max_length=500)),
            ],
        ),
    ]
