# Generated by Django 3.0.6 on 2020-11-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20201123_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='releasedON',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seriesdata',
            name='releasedON',
            field=models.DateTimeField(),
        ),
    ]
