# Generated by Django 3.0.6 on 2020-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='seriesdata',
            name='disc',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='seriesdata',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='seriesdata',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
