# Generated by Django 3.0.6 on 2020-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20201123_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='desc',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='seriesdata',
            name='desc',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
