# Generated by Django 3.1.2 on 2020-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20201125_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='releasedON',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriesdata',
            name='releasedON',
            field=models.DateField(blank=True, null=True),
        ),
    ]
