# Generated by Django 3.1.2 on 2020-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20201127_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='platform',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seriesdata',
            name='platform',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
