# Generated by Django 3.1.2 on 2020-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20201127_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='trailer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seriesdata',
            name='trailer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
