# Generated by Django 3.1.2 on 2020-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201127_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
