# Generated by Django 3.1.2 on 2020-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20201130_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='poster2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
