# Generated by Django 3.1.2 on 2020-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_moviedata_poster2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdata',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seriesdata',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seriesdata',
            name='poster2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='seriesdata',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
